#!/bin/bash
# generate-secrets.sh
#
# Generates Relay/Generated/Secrets.swift with XOR-obfuscated API keys.
# Called as a Run Script build phase before compilation.
#
# Build settings consumed (set via Secrets.xcconfig):
#   GIPHY_API_KEY  – GIPHY API key (optional)

set -euo pipefail

OUTPUT_DIR="${SRCROOT}/Relay/Generated"
OUTPUT_FILE="${OUTPUT_DIR}/Secrets.swift"

mkdir -p "${OUTPUT_DIR}"

# --- helpers ---

# xor_obfuscate KEY_VALUE
#   Prints two Swift array literals: the random pad and the XOR'd cipher bytes.
xor_obfuscate() {
    local value="$1"
    local len=${#value}
    local pad_bytes=()
    local cipher_bytes=()

    for (( i = 0; i < len; i++ )); do
        # Random byte 1–255 (avoid 0 to prevent trivial patterns)
        local r=$(( (RANDOM % 254) + 1 ))
        # ASCII value of character
        local c=$(printf '%d' "'${value:$i:1}")
        local x=$(( r ^ c ))
        pad_bytes+=("0x$(printf '%02x' "$r")")
        cipher_bytes+=("0x$(printf '%02x' "$x")")
    done

    local pad_str
    pad_str=$(IFS=', '; echo "${pad_bytes[*]}")
    local cipher_str
    cipher_str=$(IFS=', '; echo "${cipher_bytes[*]}")

    echo "        nonisolated static let p: [UInt8] = [${pad_str}]"
    echo "        nonisolated static let c: [UInt8] = [${cipher_str}]"
}

# --- main ---

GIPHY_KEY="${GIPHY_API_KEY:-}"

{
    cat <<'HEADER'
// Secrets.swift
// Auto-generated by scripts/generate-secrets.sh — DO NOT EDIT.

/// Build-time secrets, XOR-obfuscated to avoid plain-text exposure in the
/// binary. Not a substitute for server-side key management, but prevents
/// casual extraction via `strings` or plist inspection.
enum Secrets {

    /// Decodes an XOR-obfuscated byte pair into a ``String``.
    private nonisolated static func decode(pad: [UInt8], cipher: [UInt8]) -> String? {
        guard pad.count == cipher.count, !pad.isEmpty else { return nil }
        return String(decoding: zip(pad, cipher).map(^), as: UTF8.self)
    }

HEADER

    if [ -n "$GIPHY_KEY" ]; then
        echo '    private enum GiphyStorage: Sendable {'
        xor_obfuscate "$GIPHY_KEY"
        echo '    }'
        echo ''
        echo '    nonisolated(unsafe) static var giphyAPIKey: String? { decode(pad: GiphyStorage.p, cipher: GiphyStorage.c) }'
    else
        echo '    nonisolated(unsafe) static var giphyAPIKey: String? { nil }'
    fi

    echo '}'
    echo ''
} > "${OUTPUT_FILE}"
